### PR TITLE
feature: more item-related Minecraft improvements

### PR DESCRIPTION
**Pull request by broccolai**
reopened of #28 because of branch change

### CODE REVIEW

**Comment by TehBrian** [comment]
to-do:
- ensure 100% item API coverage. (check all ItemMetas for missing methods.)

**Comment by TehBrian** [comment]
> It's annotated with @NotNull, and says to do the check so I guess we just use the #hasVariant and return null

variant is internally stored as a nullable integer, and #hasVariant is just: `public boolean hasVariant() { return this.variant != null; }`, but #getVariant does an enum values array lookup, so if !hasVariant, #getVariant will throw some error. not sure if that's just decompiler stuff but idc, I'll switch #has methods over to nullable getters.

**Comment by TehBrian** [comment]
thoughts on renaming TropicalFishBucketMeta#variant -> #hasVariant? since it's not a plain getter (it's calculated from deviations from the norm of the three pattern and color variables), the modern convention of dropping prefixes from getts and setters doesn't apply here.

it would be a breaking API change for something really fuzzy/subjective, so it's probably not even worth it.

**Comment by broccolai** [comment]
> > It's annotated with @NotNull, and says to do the check so I guess we just use the #hasVariant and return null
> 
> variant is internally stored as a nullable integer, and #hasVariant is just: `public boolean hasVariant() { return this.variant != null; }`, but #getVariant does an enum values array lookup, so if !hasVariant, #getVariant will throw some error. not sure if that's just decompiler stuff but idc, I'll switch #has methods over to nullable getters.

Yeah, even if it internally returns null on get, i think it's better to follow the api just incase

**Comment by broccolai** [comment]
> thoughts on renaming TropicalFishBucketMeta#variant -> #hasVariant? since it's not a plain getter (it's calculated from deviations from the norm of the three pattern and color variables), the modern convention of dropping prefixes from getts and setters doesn't apply here.
> 
> it would be a breaking API change for something really fuzzy/subjective, so it's probably not even worth it.

I prefer this, package has changed anyway so no point worry about breaking api

**Comment by TehBrian** [comment]
> I prefer this, package has changed anyway so no point worry about breaking api

the #hasVariant, that is?

**Comment by TehBrian** [comment]
deleting this branch/pr and making a new one b/c merging is hard >///< and I'd rather just make new commits lmfao

**Pull request closed without merging**
